# This is a basic workflow to help you get started with Actions
name: Matrix Build

# Set the job to run manually
on:
  push:
    branches-ignore: main

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 2
      matrix:
        run: ['run1', 'run2', 'run3']
    steps:
    - name: Matrix job ${{ matrix.run }}
      run:  |
        echo Run ${{ matrix.run }}
        date
        sleep 15
        date
