---
##########################
##########################
## CodeQL Security Scan ##
##########################
##########################
name: CodeQl Analysis

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://github.com/github/codeql-action
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'

###############
# Set the Job #
###############
jobs:
  scan:
    # Name the Job
    name: CodeQL Analysis
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      #####################
      # Initialize CodeQL #
      #####################
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python


      - name: Wait for app build success
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build-success
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: CI
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Perform CodeQL
        if: steps.wait-for-build-success.outputs.conclusion == 'success'
        uses: github/codeql-action/analyze@v1

      - name: Error message on failure
        if: steps.wait-for-build-success.outputs.conclusion == 'failure'
        run: echo "ERROR! Build failure, not running security!
        
